"""empty message

Revision ID: 809bc5c428d3
Revises: c8ec93aedaa6
Create Date: 2022-04-19 14:35:40.533545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809bc5c428d3'
down_revision = 'c8ec93aedaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('save_keys', sa.Column('ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('save_keys', 'ip')
    # ### end Alembic commands ###
