"""empty message

Revision ID: 9ca81b8c01b0
Revises: 
Create Date: 2022-03-24 22:15:16.055287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca81b8c01b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pcname', sa.String(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save_keys')
    # ### end Alembic commands ###
